name: autotools-msys2

on:
  push:
    branches: [ "master", "devel",
      "citest",
      "citest-autotools",
      "citest-autotools-msys2" ]
    tags:
      - '**'
  pull_request:
    branches: [ "master", "devel" ]

jobs:
  msys2:
#    if: false
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 '{0}'
    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2.22.0
      with:
        update: true
        install: autotools diffutils mingw-w64-x86_64-check mingw-w64-x86_64-toolchain
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --prefix=/tmp/adflib
    - name: make
      run: make
    - name: make check
      #run: ( make check || grep . examples/*.log examples/tests/*.log )
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: make install
      run: make install
    - name: check installation
      run: find /tmp/adflib -iname '*adf*'
    - name: test installed command-line utils
      run: ./examples/tests/test-all-examples.sh /tmp/adflib/bin
    - name: store logs from failed tests
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: msys2_autotools_logs_failed_tests
        path: |
          examples/tests/*.log
          regtests/Test/*.log
          tests/*.log
