name: ADFlib autotools

on:
  push:
    branches: [ "citest" ]
  pull_request:
    branches: [ "citest" ]

jobs:
  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install prereq.
      run: sudo apt-get update ; sudo apt-get install -y check
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make install
      run: sudo make install
    - name: check installation
      run: find /usr/local/bin ; ls /usr/local/lib/*.so*
    - name: update ldconfig
      run: sudo ldconfig
    - name: try unadf
      run: unadf -r arccsh.adf
    - name: try adf_show_metadata device
      run: adf_show_metadata arccsh.adf
    - name: try adf_show_metadata file
      run: adf_show_metadata arccsh.adf CSH
    - name: try adf_show_metadata dir
      run:
        adf_show_metadata arccsh.adf c/ ;
        adf_show_metadata arccsh.adf l
    - name: try adf_create_floppy
      run: adf_floppy_create testflopdd1.adf dd
    - name: try adf_create_floppy
      run: adf_floppy_format testflopdd1.adf TestFlopDD1 1
    - name: try adf_show_metadata on created floppy
      run: adf_show_metadata testflopdd1.adf
