name: ADFlib CMake

on:
  push:
    branches: [ "citest" ]
  pull_request:
    branches: [ "citest" ]

jobs:
  build_and_test_ubuntu_cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install prereq.
      run: sudo apt-get update ; sudo apt-get install -y check
    - name: cmake_shared_configure
      run: util/cmake_shared_configure
    - name: cmake_shared_build
      run: util/cmake_shared_build
    - name: cmake_shared_test
      run: util/cmake_shared_test
    - name: cmake_shared_install
      run: sudo bash util/cmake_shared_install
    - name: check installation
      run: find /usr/local -iname '*adf*'
    - name: update ldconfig
      run: sudo ldconfig
    - name: test command-line utils
      run: util/test_examples
