name: cmake-cross-mingw

on:
  push:
    branches: [
    "master",
    "devel",
    "citest",
    "citest-cmake",
    "citest-cmake-cross-mingw" ]
    tags:
      - '**'
  pull_request:
    branches: [ "master", "devel" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
#        build_type: [ x86_64, i686 ]
        build_type: [ x86_64 ]
    steps:
    - uses: actions/checkout@v4
    - name: install prereq.
      run: |
        sudo apt-get update
        sudo apt-get install -y check gcc-mingw-w64-x86-64-win32
    - name: cmake_shared_configure
      run: |
        CC=${{ matrix.build_type }}-w64-mingw32-gcc \
        util/cmake_shared_configure \
        -DADFLIB_ENABLE_TESTS=OFF
    - name: cmake_shared_build
      run: util/cmake_shared_build
#    - name: cmake_shared_test
#      run: util/cmake_shared_test
#    - name: cmake_shared_install
#      run: sudo bash util/cmake_shared_install
#    - name: check installation
#      run: find /usr/local -iname '*adf*'
#    - name: update ldconfig
#      run: sudo ldconfig
#    - name: test command-line utils
#      run: ./tests/examples/test_all_examples.sh /usr/local/bin
    - name: check build output files
      run: find build/
    - name: prepare artifact
      run: |
        mkdir -vp artifacts/bin
        cp -v build/shared/src/libadf* artifacts/bin/
        cp -v build/shared/examples/*.exe artifacts/bin/
        mkdir -v artifacts/include
        cp -vR src/*.h artifacts/include
        cp -vR BUGS.md \
               NOTES.md \
               README.md \
               COPYING* \
               AUTHORS \
               ChangeLog \
               TODO \
               doc \
               artifacts/
        cd artifacts ; \
        tar cvzf ../adflib-mingw-${{ matrix.build_type }}.tgz *
        cd ..
    - uses: actions/upload-artifact@v4
      with:
#        name: adflib-${{ env.ADFLIB_TAG }}-mingw
        name: adflib-mingw-${{ matrix.build_type }}
        path: |
          adflib-mingw-${{ matrix.build_type }}.tgz

  test:
    needs: build
    runs-on: windows-latest
    strategy:
      matrix:
#        build_type: [ x86_64, i686 ]
        build_type: [ x86_64 ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
#      name: adflib-${{ env.ADFLIB_TAG }}-mingw
        name: adflib-mingw-${{ matrix.build_type }}
        path: .
    - name: extract file from the artifact
      run: tar xzvf adflib-mingw-${{ matrix.build_type }}.tgz
    - name: list files extracted from the artifact
      shell: bash
      run: find bin/
    - name: show properties of binaries (installed)
      shell: bash
      run: ldd bin/unadf
    - name: configure tests
      shell: bash
      run: |
        cat tests/config.sh.in_cmake | \
          sed -e 's@\${PROJECT_BINARY_DIR}@./bin/@' \
              -e 's@\${PROJECT_SOURCE_DIR}@./@' \
          > tests/config.sh
        cat tests/config.sh
    - name: test command-line utils
      shell: bash
      run: |
        tests/examples/test_examples_basic.sh bin/
        tests/examples/test_all_examples.sh bin/
    - name: test installed command-line utils (2)
      shell: bash
      run: |
        ./tests/examples2/run_all_tests.sh bin
    - name: store logs from failed tests
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: cmake_cross_mingw_${{ matrix.build_type }}_logs_failed_tests
        path: |
          cmake/shared/Testing/
