name: ADFlib CMake

on:
  push:
    branches: [ "master", "devel", "citest", "citest-deb" ]
    tags:
      - '**'
  pull_request:
    branches: [ "master", "devel" ]

jobs:
  ubuntu_cmake_shared:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install prereq.
      run: sudo apt-get update ; sudo apt-get install -y check
    - name: cmake_shared_configure
      run: util/cmake_shared_configure
    - name: cmake_shared_build
      run: util/cmake_shared_build
    - name: cmake_shared_test
      run: util/cmake_shared_test
    - name: cmake_shared_install
      run: sudo bash util/cmake_shared_install
    - name: check installation
      run: find /usr/local -iname '*adf*'
    - name: update ldconfig
      run: sudo ldconfig
#    - name: test command-line utils
#      run: util/test_examples

  ubuntu_cmake_debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install prereq.
      run: sudo apt-get update ; sudo apt-get install -y check
    - name: cmake_debug_configure
      run: util/cmake_debug_configure
    - name: cmake_debug_build
      run: util/cmake_debug_build
    - name: cmake_debug_test
      run: util/cmake_debug_test
    - name: cmake_debug_install
      run: sudo bash util/cmake_debug_install
    - name: check installation
      run: find /usr/local -iname '*adf*'
    - name: update ldconfig
      run: sudo ldconfig
#    - name: test command-line utils
#      run: util/test_examples

  windows_cmake_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: install prereq.
      run: |
        choco install ninja cmake
        ninja --version
        cmake --version
    - name: cmake_shared_configure
      shell: bash
      run: util/cmake_shared_configure
    - name: cmake_shared_build
      shell: bash
      run: util/cmake_shared_build
    - name: copy binaries to orig. dirs
      shell: bash
      run: |
        cp -v build/shared/regtests/Test/Debug/*.exe build/shared/regtests/Test/
        cp -v build/shared/tests/Debug/*.exe build/shared/tests/
        cp -v build/shared/examples/Debug/*.exe build/shared/examples/
    - name: copy dll to dirs with test exe
      shell: bash
      run: |
        cp -v build/shared/src/Debug/*.dll build/shared/regtests/Test/
        cp -v build/shared/src/Debug/*.dll build/shared/tests/
        cp -v build/shared/src/Debug/*.dll build/shared/examples/
    - name: cmake_shared_test
      shell: bash
      run: util/cmake_shared_test
#    - name: cmake_shared_install
#      shell: bash
#      run: util/cmake_shared_install
    - name: check build files
      shell: bash
      run: |
        pwd
        find
    - name: prepare artifacts
      shell: bash
      run: |
        mkdir -p artifacts/bin
        cp -v build/shared/src/Debug/*.dll \
              build/shared/examples/Debug/*.exe \
              artifacts/bin
        mkdir artifacts/include
        cp -vR src/*.h artifacts/include
        cp -vR README.md \
               COPYING \
               AUTHORS \
               ChangeLog \
               doc \
               artifacts/
    - name: set env
      shell: bash
      run: echo "ADFLIB_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      shell: bash
      run: |
        echo $ADFLIB_TAG
        echo ${{ env.ADFLIB_TAG }}
    - uses: actions/upload-artifact@v3
      with:
#        name: adflib-${{ env.ADFLIB_TAG }}-windows
        name: adflib-windows
        path: |
          artifacts/
    - name: archive examples/tests
      shell: bash
      run: |
        mkdir -v artifact-tests
        tar cvzf artifact-tests/examples_tests.tgz examples/tests/
    - uses: actions/upload-artifact@v3
      with:
        name: adflib-examples-tests
        path: |
          artifact-tests

  windows_cmake_test:
    runs-on: windows-latest
    needs: windows_cmake_build
    steps:
    - uses: actions/download-artifact@master
      with:
#        name: adflib-${{ env.ADFLIB_TAG }}-windows
        name: adflib-windows
        path: .
    - name: list files extracted from the artifact
      shell: bash
      run: find .
    - uses: actions/download-artifact@master
      with:
        name: adflib-examples-tests
        path: .
    - name: extract examples/tests
      shell: bash
      run: tar xvzf examples_tests.tgz
    - name: test command-line utils
      shell: bash
      run: ./examples/tests/test-all-examples.sh bin

  macos_cmake_shared:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: install prereq.
      run: |
        brew install cmake ninja coreutils
        ninja --version
        cmake --version
        gstdbuf --version
    - name: cmake_shared_configure
      run: util/cmake_shared_configure
    - name: cmake_shared_build
      run: util/cmake_shared_build
    - name: cmake_shared_test
      run: util/cmake_shared_test
    - name: cmake_shared_install
      run: sudo bash util/cmake_shared_install
    - name: check installation
      run: find /usr/local -iname '*adf*'
#    - name: update ldconfig
#      run: sudo ldconfig
#    - name: test command-line utils
#      run: util/test_examples
