name: ADFlib deb build/packaging

on:
  push:
    branches: [ "citest" ]
  pull_request:
    branches: [ "citest" ]

jobs:
  build_and_test_deb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install prereq.
      run:
        sudo apt-get update &&
        sudo apt-get install -y check devscripts debhelper
    - name: debuild
      run: util/deb_build.sh
    - name: list packages
      run: ls ..
    - name: install packages
      run: sudo dpkg -i ../*.deb
    - name: check installation
      run:
        dpkg -l 'libadf*' ;
        dpkg -l 'libadf*' | grep "libadf" |
        cut -d' ' -f 3 | cut -d':' -f 1 | xargs dpkg -L
    - name: test command-line utils
      run: util/test_examples
